### ISSUE TITLE
Intégration QRadar

### ISSUE THREAD

**Issue by tarraschk** [Cyberwatch/cyberwatch_api_toolbox#108]
QRadar a une édition communautaire, ce serait pratique qu'on propose quelques scripts basiques d'intégration par API :)

https://developer.ibm.com/qradar/ce/

**Comment by tarraschk** [comment]
On a notamment eu des demandes pour envoyer ce qu'on a comme infos sur les serveurs vers QRadar

**Comment by fwininger** [comment]
On attend d'avoir la nouvelle API v3 a disposition pour éviter de développer dans le vide.

Cela devrait être possible d'ici la fin de l'année.
