### ISSUE TITLE
Faire ceci avec une CI et revoker toutes les clés générées.

### ISSUE THREAD

**Issue by fwininger** [Cyberwatch/cyberwatch_api_toolbox#187]
Faire ceci avec une CI et revoker toutes les clés générées.

+ indiquer le processus pour la mise à jour des numéros de version.

_Originally posted by @fwininger in https://github.com/Cyberwatch/cyberwatch_api_toolbox/pull/185/review_comment/create_

**Comment by hezanathos** [comment]
https://github.com/Cyberwatch/cyberwatch_api_toolbox/pull/190/files#
