### ISSUE TITLE
Air gapped scans : Compliance

### ISSUE THREAD

**Issue by PierreHachard** [Cyberwatch/cyberwatch_api_toolbox#254]
Right now, Air gapped scripts only implement a way to fetch the vulnerability module scripts

We should implement the possibility to fetch compliance scripts (and upload the results aswell).

As there is a large amount of compliance scripts, filtering mecanism should also be implemented. We should be able to fetch compliance scripts with different options : 
- filter based on compliance repository AND the os_key (same implementation as what's currently in importer)
- any other interesting way of filtering we may think of
- possibility to fetch ALL the scripts ? (not sure it is actually a good idea)

**Comment by hezanathos** [comment]
It has been achieved with CLI
