### ISSUE TITLE
cyberwatch-cli airgap should have an option to present all available system OS

### ISSUE THREAD

**Issue by jljuan** [Cyberwatch/cyberwatch_api_toolbox#259]
The sub-command download-compliance-scripts use a mandatory option --os.
The documentation doesn't present exemples nor exhaustive list of expected value.
It could be interesting to have an option like "--os-list" to present to the user the possible list of OS it can use as value for the option.

**Comment by fwininger** [comment]
@jljuan thanks for reporting this issue. 
I open an issue on our internal issue tracker to add a route in our API to retrive the list of OS.

**Comment by fwininger** [comment]
@polyedre a new route have been added on Cyberwatch 10.7.0. Can you implement the CLI change ?

**Comment by fwininger** [comment]
@jljuan you need to wait Cyberwatch 10.7.0 and update the python module. Thanks for the suggestion.
