### ISSUE TITLE
Documentation README.md error

### ISSUE THREAD

**Issue by jljuan** [Cyberwatch/cyberwatch_api_toolbox#261]
The line 18 from cyberwatch_api_toolbox/README.md point to:

`[Library Documentation](#library-documentation)`

while it is expected:

`[Command line Documentation](#command-line-documentation)`

**Comment by fwininger** [comment]
Thanks @jljuan for reporting this issue.

**Comment by jljuan** [comment]
While correcting this point, can you also take into account that the python API used in the page `https://docs.cyberwatch.fr/api/en/#cyberwatch_importer` is no more accurate.

The interface now use **<fetch/upload>_airgapped_<script(s)/result(s)>**

**Comment by fwininger** [comment]
@hezanathos can you fix this issue ?
