### ISSUE TITLE
Give example of remote access creation with server_groups parameter

### ISSUE THREAD

**Issue by hezanathos** [Cyberwatch/cyberwatch_api_toolbox#63]
Update documentation and existing examples to display usage of the new server_groups parameter for ram creation.

**Comment by tarraschk** [comment]
Paul, merci de traiter ce ticket.

L'idée est de : 
- [ ] reprendre le script examples/create_remote_access.py et en faire une copie nommée examples/create_remote_access_with_groups.py
- [ ] ce script examples/create_remote_access_with_groups.py devra créer des remote_accesses sur notre API avec des groupes, via le paramètre "server_groups" (à ajouter).
- [ ] il faut également documenter ton code pour que toute personne puisse le comprendre.

Le paramètre server_groups permet de lister les groupes que tu veux ajouter à la machine que tu crées.

Je t'envoie des clés d'API pour faire tes tests.

**Comment by fwininger** [comment]
L'idée est de :

- [ ] ne pas dupliquer de code
- [ ] modifier le fichier examples/create_remote_access.py pour créer des remote_accesses sur notre API avec des groupes, via le paramètre "server_groups" (à ajouter).
- [ ] il faut également documenter ton code pour que toute personne puisse le comprendre.
- [ ] corriger le fichier pour envoyer les groupes à la création du remote_access et supprimer la mise à jour de compliance_groupes dans ce fichier, mettre à jour les tests et le fichier d'exemple qui utilise cette méthode. https://github.com/Cyberwatch/cyberwatch_api_toolbox/blob/50345ca5cd4f16800349184ba552695a493bfec0/cbw_api_toolbox/cbw_file_xlsx.py#L17
