### ISSUE TITLE
Lancer des tests_deploys par API

### ISSUE THREAD

**Issue by tarraschk** [Cyberwatch/cyberwatch_api_toolbox#66]
Cyberwatch 9.14 permet de lancer des test_deploy par API.

La requête est :

```
GET /api/v2/remote_accesses/:id/test_deploy
```

=> Il faut maintenant : 

- [ ] Adapter cbw_api_toolbox/cbw_api.py et créer une méthode "test_deploy_remote_access" qui prend en paramètre (self, remote_access_id) et qui exécute test_deploy sur remote_access ;
- [ ] Faire un script d'exemple qui commence par récupérer tous les remote_accesses (appel sur remote_access) puis identifie ceux qui sont invalides, puis lance un test_deploy sur chaque remote_access invalide ;
- [ ] Tests unitaires (super important).

**Comment by fwininger** [comment]
Ne pas oublier les tests de la feature. Merci
